server:
  port: 8092

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://mongodb:27017/users

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka
