server:
  port: 8083

spring:
  application:
    name: annonce-service
  data:
    mongodb:
      uri: mongodb://mongodb:27017/annonce

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
