server:
  port: 8088

spring:
  application:
    name: appartement-service
  data:
    mongodb:
      uri: mongodb://mongodb:27017/appartments

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
