server:
  port: 9998  # Port du Config Server

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/unesFou/config-repo.git  # Remplace avec l'URL de ton repo Git
          #uri: file:///git
          clone-on-start: true  # Cloner le repo au démarrage
          default-label: main  # Branche par défaut
            force-pull: true  # Add this

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka

logging:
  level:
    root: DEBUG
    org.springframework.cloud.config: DEBUG
