server:
  port: 9998  # Port du Config Server

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          #uri: file:///C:/Users/Fujitsu/Documents/MasterIAO/IAO MASTER M2/Project-Backend-Pfe/config-repo/
          uri: https://github.com/unesFou/config-repo.git
          searchPaths: '{application}'
          username: unesFou
          password: unes1989
          clone-on-start: true
          default-label: main
      refreshRate: 0

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka

logging:
  level:
    root: DEBUG
    org.springframework.cloud.config: DEBUG
