server:
  port: 8084

spring:
  application:
    name: reservation-service
  data:
    mongodb:
      uri: mongodb://mongodb:27017/reservation

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
